######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 19 23:11:44 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += DisplayGUI.h
SOURCES += ClientGUI.cpp DisplayGUI.cpp
