######################################################################
# Automatically generated by qmake (2.01a) Sun Jul 20 09:22:15 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += DisplayGUI.h LoginGUI.h MainWindow.h MessageGUI.h
SOURCES += ClientGUI.cpp \
           DisplayGUI.cpp \
           LoginGUI.cpp \
           MainWindow.cpp \
           MessageGUI.cpp
