######################################################################
# Automatically generated by qmake (2.01a) Sun Jun 1 16:55:04 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ClientSock.h EinClient.h ../Include/Network.h
SOURCES += ClientMain.cpp ClientSock.cpp EinClient.cpp
