######################################################################
# Automatically generated by qmake (2.01a) Sun Apr 6 00:27:35 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ClientSock.h EinClient.h MainWindow.h ../Include/Network.h
SOURCES += ClientMain.cpp ClientSock.cpp EinClient.cpp MainWindow.cpp
